version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./static:/app/static
    environment:
      - CUDA_VISIBLE_DEVICES=0

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend